### ISSUE TITLE
[Cadastro] Cadastrar usuário - Backend 

### ISSUE THREAD

**Issue by schroderfernando16** [ES-UFABC/SMA-Handshake-Eng-Software-2022.1-#1]
**TASKS**

- [x] Criar tabela de usuários com os campos:
```
{
  "id": "integer",
  "nome": "string",
  "telefone": "string",
  "email": "string",
  "logradouro": "string",
  "numero": "integer",
  "complemento": "string",
  "cep": "string",
  "cidade": "string",
  "estado": "string",
  "cpf": "string",
  "cnpj": "string",
  "produtor": "bool",
  "senha": "string"
}
```
- [x] Criar model para usuário
- [x] Criar método POST para gravar informações no banco de dados

**Comment by Hespius** [comment]
- [ ] Criar modulo agricultar
