### ISSUE TITLE
[Login] Criar tela de login - Frontend

### ISSUE THREAD

**Issue by caiiquesantos** [ES-UFABC/SMA-Handshake-Eng-Software-2022.1-#11]
**DESCRIÇÃO:**

> Enquanto produto desejo que seja desenvolvida a tela de login para que seja utilizada por clientes e agricultores.

**OBJETIVO:**

> Quando finalizada a tela deve conter todos os campos informados no detalhes técnicos e está funcional, fazendo as validações necessárias em cada campo.

**CENÁRIO:**

> Dado que o usuário deseje fazer login
> Quando clicar em login
> Então deve ser exibida a tela do login
> E o backend deve reconhecer qual o tipo de user
> E enviar as informações para que o frontend exiba a tela correta

DETALHES TÉCNICOS:

Login/autenticação básica do usuário:

- email
- senha

**TASKS**
- [x] Criar campo para inserir o e-mail do usuário
- [x] Criar campo para inserir a senha do usuário
- [x] Criar botão para realizar login
- [x] Criar método de requisição do login para o backend

<h6>LOGIN VÁLIDO</h6>

- [x] Exibir nome do usuário no menu
- [x] Ocultar campo de e-mail e senha
- [x] Ocultar botão de realizar login
- [x] Ocultar "Cadastra-se"

<h6>LOGIN INVÁLIDO</h6>

- [x] Apresentar mensagem de falha
