### ISSUE TITLE
[Produtor] Dashboard de Tracking financeiro 

### ISSUE THREAD

**Issue by antunesvitor** [ES-UFABC/SMA-Handshake-Eng-Software-2022.1-#50]
Criação da tela de BI do produtor
Irá conter informações financeiras de seu negócio

- [x] Gráfico de venda ao longo do tempo exibindo sua receita mês a mês (linha)

- [x] Gráfico de distribuição de produtos vendidos (pizza)

- [x] Gráfico de volume financeiro mensal distribuido por commodities (barra de níveis)
