### ISSUE TITLE
[Cadastro] Criar tela de cadastro do usuário - Frontend

### ISSUE THREAD

**Issue by caiiquesantos** [ES-UFABC/SMA-Handshake-Eng-Software-2022.1-#9]
**DESCRIÇÃO:**

> Enquanto produto desejo que seja desenvolvido o formulário de cadastro onde os nossos clientes possam informar seus dados e criar uma conta na nossa plataforma.

**OBJETIVO:**

> Quando finalizada a tela deve conter todos os campos informados no detalhes técnicos e está funcional, fazendo as validações necessárias em cada campo.

**CENÁRIO:**

> Dado que o cliente acesse nosso site
> Quando clicar em cadastrar
> Então deve ser exibida a tela do formulário

**DETALHES TÉCNICOS:**

Cadastro de consumidores com os seguintes itens no formulário:

- nome (aceita somente texto)
- telefone (aceita apenas números)
- email (valida se é um email válido)
- CPF (verificar se é um cpf válido e aceita apenas números)
- logradouro (aceita somente texto)
- numero (aceita apenas números)
- complemento (opcional)
- cep (aceita apenas números)
- cidade (aceita apenas textos)
- estado (escolhe de uma lista disponível)
- senha 
- confirmar senha

**TASKS**
- [x] Criar combobox para usuário escolher se irá criar um perfil de consumidor ou produtor
- [x] Criar campo para cadastrar o nome do usuáio
- [x] Criar campo para cadastrar telefone
- [x] Criar campo para cadastrar e-mail
- [x] Criar campo para cadastrar CPF/CNPJ
- [x] Criar campo para cadastrar logradouro
- [x] Criar campo para cadastrar número da residência
- [x] Criar campo para inserir complemento
- [x] Criar campo para cadastrar CEP
- [x] Criar campo para inserir a cidade
- [x] Criar combobox para escolher o estado
- [x] Criar campo para cadastrar senha
- [x] Criar campo para confirmação da senha
- [x] Criar validação para confirmação da senha
- [x] Criar método para cadastrar as informações do formulário no backend
